name: Deploy to Azure Web App

on:
  push:
    branches:
      - master # Of main, afhankelijk van je standaard branch naam

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' # Vervang dit door de Python-versie die je gebruikt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bolcom' # Vervang dit door de naam van je Azure Web App
        # slot-name: 'production' # Als je geen deployment slot gebruikt, kan dit worden weggelaten
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # De publish profile moet worden ingesteld in je repository secrets
        package: .
